### ISSUE TITLE
Install with Devtools failed

### ISSUE THREAD

**Issue by Btibert3** [war-on-ice/nhlscrapr#1]
I wanted to play around with the package, but installation using `devtools::install_github("war-on-ice/nhlscrapr")` failed on both my Mac and Windows machines.  

Here is the error that I get on my Mac

```
** testing if installed package can be loaded
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/Library/Frameworks/R.framework/Versions/3.2/Resources/library/nhlscrapr/libs/nhlscrapr.so':
  dlopen(/Library/Frameworks/R.framework/Versions/3.2/Resources/library/nhlscrapr/libs/nhlscrapr.so, 6): no suitable image found.  Did find:
    /Library/Frameworks/R.framework/Versions/3.2/Resources/library/nhlscrapr/libs/nhlscrapr.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/Library/Frameworks/R.framework/Versions/3.2/Resources/library/nhlscrapr’
Error: Command failed (1)
```

**Comment by mannyelk** [comment]
Brock,

I actually had trouble installing nhlscrapr this way too. Try downloading the tar.gz from this link: https://www.dropbox.com/s/5ana5jztwl1j2wz/nhlscrapr_1.10.8.tar.gz?dl=0.

[https://cf.dropboxstatic.com/static/images/icons128/page_white_compressed.png]https://www.dropbox.com/s/5ana5jztwl1j2wz/nhlscrapr_1.10.8.tar.gz?dl=0

nhlscrapr_1.10.8.tar.gzhttps://www.dropbox.com/s/5ana5jztwl1j2wz/nhlscrapr_1.10.8.tar.gz?dl=0
www.dropbox.com
Shared with Dropbox

You should then be able to install from the RStudio console under Tools > Install Packages.

Let me know if you run into any problems,
Manny

**Comment by Btibert3** [comment]
Thanks for the quick reply. That totally did the trick.

Brock
